import type { NavigationItem } from './navigation.types';

export const NAVIGATION_CONFIG: NavigationItem[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    href: '/score/dashboard',
    icon: 'LayoutDashboard',
    module: 'core',
    order: 10,
  },
  {
    key: 'risk-linear',
    label: 'Riesgo lineal',
    href: '/score/evaluacion/lineal-assessment',
    icon: 'BarChart3',
    module: 'linear-risk',
    permission: 'risk.linear.read',
    order: 20,
  },
  {
    key: 'simulation',
    label: 'Simulación',
    icon: 'FlaskConical',
    module: 'simulation',
    permission: 'simulation.read',
    order: 21,
    children: [
      {
        key: 'simulation-failures',
        label: 'Fallas de controles',
        href: '/app-simulation',
        icon: 'ShieldX',
        module: 'simulation',
        permission: 'simulation.read',
        order: 211,
      },
      {
        key: 'simulation-montecarlo',
        label: 'Monte Carlo',
        href: '/score/simulacion/monte-carlo',
        icon: 'Binary',
        module: 'simulation',
        permission: 'simulation.read',
        order: 212,
      },
    ],
  },
  {
    key: 'benchmark',
    label: 'Benchmarking',
    href: '/score/dashboard',
    icon: 'Trophy',
    module: 'benchmark',
    permission: 'benchmark.read',
    order: 22,
  },
  {
    key: 'operation',
    label: 'Operación',
    icon: 'Clock3',
    module: 'core',
    order: 30,
    children: [
      {
        key: 'risk-tracking',
        label: 'Seguimiento',
        href: '/score/evaluacion/seguiminto',
        icon: 'Clock3',
        module: 'linear-risk',
        permission: 'risk.linear.read',
        order: 31,
      },
      {
        key: 'risk-significant-activity',
        label: 'Actividad significativa',
        href: '/validacion/riesgo-lineal/actividad/nueva',
        icon: 'Activity',
        module: 'linear-risk',
        permission: 'risk.linear.read',
        order: 32,
      },
      {
        key: 'risk-new',
        label: 'Nuevo riesgo',
        href: '/validacion/riesgo-lineal/riesgo/nuevo',
        icon: 'ShieldAlert',
        module: 'linear-risk',
        permission: 'risk.linear.read',
        order: 33,
      },
    ],
  },
  {
    key: 'governance',
    label: 'Gobierno',
    icon: 'Scale',
    module: 'governance',
    order: 40,
    children: [
      {
        key: 'governance-parameters',
        label: 'Parámetros',
        href: '/modelo/parametros',
        icon: 'SlidersHorizontal',
        module: 'governance',
        permission: 'governance.parameters.read',
        order: 51,
      },
      {
        key: 'governance-versioning',
        label: 'Versionado',
        href: '/modelo/versionado',
        icon: 'GitBranch',
        module: 'governance',
        permission: 'governance.versioning.read',
        order: 52,
      },
      {
        key: 'governance-engine',
        label: 'Motor',
        href: '/score/motor',
        icon: 'Cpu',
        module: 'governance',
        permission: 'governance.engine.read',
        order: 53,
      },
      {
        key: 'governance-objectives',
        label: 'Objetivo',
        href: '/dashboard/riesgo/registro/objetivos',
        icon: 'Target',
        module: 'governance',
        permission: 'governance.objectives.read',
        order: 54,
      },
      {
        key: 'governance-ontology',
        label: 'Ontología',
        href: '/modelo/gobernanza/ontologia',
        icon: 'Network',
        module: 'governance',
        permission: 'governance.objectives.read',
        order: 55,
      },
      {
        key: 'governance-company',
        label: 'Empresa',
        href: '/admin/empresa',
        icon: 'BriefcaseBusiness',
        module: 'core',
        order: 56,
      },
      {
        key: 'governance-users',
        label: 'Usuarios',
        href: '/admin/usuarios',
        icon: 'Users',
        module: 'core',
        order: 57,
      },
      {
        key: 'governance-roles',
        label: 'Roles',
        href: '/admin/roles',
        icon: 'Shield',
        module: 'core',
        order: 58,
      },
      {
        key: 'governance-security',
        label: 'Seguridad',
        href: '/seguridad',
        icon: 'Shield',
        module: 'security',
        order: 59,
      },
      {
        key: 'governance-license-management',
        label: 'License Management',
        href: '/modelo/gobernanza',
        icon: 'Scale',
        module: 'governance',
        permission: 'governance.license.read',
        order: 60,
      },
    ],
  },
];
