import type { NavigationItem } from './navigation.types';

export const NAVIGATION_CONFIG: NavigationItem[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    href: '/score/dashboard',
    icon: 'LayoutDashboard',
    module: 'core',
    order: 10,
  },
  {
    key: 'risk',
    label: 'Core',
    icon: 'ShieldAlert',
    module: 'core',
    order: 20,
  },
  {
    key: 'alerts',
    label: 'Alertas de riesgo',
    href: '/score/alertas',
    icon: 'Bell',
    module: 'alerts',
    permission: 'alerts.read',
    order: 30,
  },
  {
    key: 'audit',
    label: 'Auditoría',
    href: '/validacion/riesgo-lineal',
    icon: 'ClipboardCheck',
    module: 'audit',
    permission: 'audit.read',
    order: 40,
  },
  {
    key: 'simulation',
    label: 'Simulación',
    icon: 'FlaskConical',
    module: 'simulation',
    permission: 'simulation.read',
    order: 50,
  },
  {
    key: 'benchmark',
    label: 'Benchmarking',
    href: '/score/dashboard',
    icon: 'Trophy',
    module: 'benchmark',
    permission: 'benchmark.read',
    order: 60,
  },
  {
    key: 'governance',
    label: 'Gobierno',
    icon: 'Scale',
    module: 'governance',
    order: 80,
  },
  {
    key: 'audit-management',
    label: 'Gestión de auditoría',
    icon: 'BriefcaseBusiness',
    module: 'audit',
    order: 100,
  },
];
