import type { NavigationItem } from './navigation.types';

export const NAVIGATION_CONFIG: NavigationItem[] = [
  {
    key: 'dashboard',
    label: 'Dashboard',
    href: '/score/dashboard2',
    icon: 'LayoutDashboard',
    module: 'core',
    order: 10,
  },
  {
    key: 'governance',
    label: 'Gobierno',
    icon: 'Scale',
    module: 'governance',
    order: 50,
    children: [
      {
        key: 'governance-admin',
        label: 'Admin',
        href: '/admin',
        icon: 'Settings',
        module: 'core',
        order: 50,
      },
      {
        key: 'governance-objectives',
        label: 'Objetivo',
        href: '/dashboard/riesgo/registro/objetivos',
        icon: 'Target',
        module: 'governance',
        permission: 'governance.objectives.read',
        order: 55,
      },
      {
        key: 'governance-company-realm',
        label: 'Macroprocesos',
        href: '/modelo/gobernanza/company-reino',
        icon: 'Building2',
        module: 'governance',
        permission: 'governance.objectives.read',
        order: 56,
      },
      {
        key: 'governance-processes',
        label: 'Procesos',
        href: '/modelo/gobernanza/company-reino/crear-proceso',
        icon: 'Workflow',
        module: 'governance',
        permission: 'governance.objectives.read',
        order: 57,
      },
      {
        key: 'governance-key-activities',
        label: 'Actividades claves',
        href: '/modelo/gobernanza/actividades-claves',
        icon: 'ListChecks',
        module: 'governance',
        permission: 'governance.objectives.read',
        order: 58,
      },
    ],
  },
  {
    key: 'risk-root',
    label: 'Gestión de riesgo',
    icon: 'ShieldAlert',
    module: 'core',
    order: 20,
    children: [
      {
        key: 'risk-context',
        label: 'Contexto',
        href: '/gestion/contexto',
        icon: 'BriefcaseBusiness',
        module: 'core',
        order: 21,
      },
      {
        key: 'risk-identify',
        label: 'Identificar riesgos',
        href: '/gestion/identificar',
        icon: 'ClipboardCheck',
        module: 'core',
        order: 22,
      },
      {
        key: 'risk-analysis',
        label: 'Análisis de riesgo',
        href: '/gestion/analisis',
        icon: 'BarChart3',
        module: 'core',
        order: 23,
      },
      {
        key: 'risk-valuation',
        label: 'Valoración de riesgo',
        href: '/gestion/valoracion',
        icon: 'Archive',
        module: 'core',
        order: 24,
      },
      {
        key: 'risk-linear',
        label: 'Riesgo lineal',
        href: '/validacion/riesgo-lineal/nueva',
        icon: 'History',
        module: 'linear-risk',
        permission: 'risk.linear.read',
        order: 211,
      },
      {
        key: 'risk-tracking',
        label: 'Seguimiento',
        href: '/score/evaluacion/seguiminto',
        icon: 'Clock3',
        module: 'linear-risk',
        permission: 'risk.linear.read',
        order: 213,
      },
      {
        key: 'risk-events',
        label: 'Eventos',
        href: '/validacion/eventos',
        icon: 'CalendarRange',
        module: 'linear-risk',
        permission: 'risk.linear.read',
        order: 214,
      },
      {
        key: 'risk-kri',
        label: 'KRI',
        href: '/validacion/kri',
        icon: 'Activity',
        module: 'linear-risk',
        permission: 'risk.linear.read',
        order: 214.5,
      },
      {
        key: 'risk-treatment',
        label: 'Tratamiento de riesgo',
        href: '/validacion/tratamiento',
        icon: 'ShieldPlus',
        module: 'linear-risk',
        permission: 'risk.linear.read',
        order: 214.6,
      },
    ],
  },
  {
    key: 'structural-risk',
    label: 'Riesgo estructural',
    icon: 'Network',
    module: 'structural-risk',
    order: 25,
    children: [
      {
        key: 'risk-structural',
        label: 'Riesgo estructural',
        href: '/score/evaluacion/structural-assessment',
        icon: 'Radar',
        module: 'structural-risk',
        permission: 'risk.structural.read',
        order: 250,
      },
      {
        key: 'structural-dashboard',
        label: 'Dashboard estructural',
        href: '/estructural/dashboard',
        icon: 'Home',
        module: 'structural-risk',
        order: 251,
      },
      {
        key: 'structural-map',
        label: 'Mapa estructural',
        href: '/estructural/mapa',
        icon: 'GitBranch',
        module: 'structural-risk',
        order: 252,
      },
      {
        key: 'structural-critical-nodes',
        label: 'Nodos críticos',
        href: '/estructural/nodos-criticos',
        icon: 'UserRoundCheck',
        module: 'structural-risk',
        order: 253,
      },
      {
        key: 'structural-dependencies',
        label: 'Dependencias',
        href: '/estructural/dependencias',
        icon: 'Cpu',
        module: 'structural-risk',
        order: 254,
      },
      {
        key: 'structural-concentration',
        label: 'Concentración',
        href: '/estructural/concentracion',
        icon: 'Layers',
        module: 'structural-risk',
        order: 255,
      },
      {
        key: 'structural-hard-gates',
        label: 'Hard gates',
        href: '/estructural/hard-gates',
        icon: 'ShieldX',
        module: 'structural-risk',
        order: 256,
      },
      {
        key: 'structural-cascades',
        label: 'Cascadas',
        href: '/estructural/cascadas',
        icon: 'Map',
        module: 'structural-risk',
        order: 257,
      },
      {
        key: 'structural-engine-config',
        label: 'Parámetros',
        href: '/modelo/parametros',
        icon: 'SlidersHorizontal',
        module: 'structural-risk',
        order: 258,
      },
    ],
  },
  {
    key: 'simulation',
    label: 'Simulaciones',
    icon: 'FlaskConical',
    module: 'simulation',
    permission: 'simulation.read',
    order: 30,
    children: [
      {
        key: 'simulation-failures',
        label: 'Fallas de controles',
        href: '/app-simulation',
        icon: 'FileText',
        module: 'simulation',
        permission: 'simulation.read',
        order: 31,
      },
      {
        key: 'simulation-montecarlo',
        label: 'Monte Carlo',
        href: '/score/simulacion/monte-carlo',
        icon: 'Binary',
        module: 'simulation',
        permission: 'simulation.read',
        order: 32,
      },
      {
        key: 'simulation-var-parametrico',
        label: 'Var paramétrico',
        href: '/score/simulacion/var-parametrico',
        icon: 'BookOpen',
        module: 'simulation',
        permission: 'simulation.read',
        order: 33,
      },
    ],
  },
  {
    key: 'monitoreo',
    label: 'Monitoreo',
    icon: 'Bell',
    module: 'core',
    order: 35,
    children: [
      {
        key: 'monitoreo-controles',
        label: 'Controles',
        href: '/monitoreo/controles',
        icon: 'CheckSquare',
        module: 'core',
        order: 36,
      },
      {
        key: 'monitoreo-riesgos',
        label: 'Riesgos',
        href: '/monitoreo/riesgos',
        icon: 'Users',
        module: 'core',
        order: 37,
      },
    ],
  },
];
