begin;

drop table if exists xdata.backup_control_eval_before_cyb_insert_batch10_12_20260329;
create table xdata.backup_control_eval_before_cyb_insert_batch10_12_20260329 as
select *
from core.control_evaluation_catalog;

create temp table tmp_cyb_group_10_12 (
  id text,
  control_id text,
  code text,
  title text,
  evaluation_guidance text,
  pass_criteria text,
  fail_criteria text,
  evaluator_steps text,
  evidence_required text,
  evidence_min_spec text,
  sample_guidance text,
  notes text,
  status text,
  is_active text,
  framework_version_id text,
  effective_from text,
  effective_to text,
  created_at text,
  updated_at text
);

copy tmp_cyb_group_10_12
from stdin
with (format text, delimiter '|', null 'NULL');
b10000001-4a22-4d8f-b001-c1a100000001|5c4d447e-7542-4594-82cf-92dfd8475148|TST-CYB-CTL046-01|Prueba operativa de deteccion y contencion de malware|Verificar que la organizacion detecta, bloquea, contiene y trata eventos de malware en endpoints, servidores o cargas relevantes con evidencia operativa real.|La muestra evidencia deteccion oportuna, accion de bloqueo o contencion, investigacion y cierre verificable.|Los eventos de malware no se detectan a tiempo, no se contienen o se cierran sin analisis y remediacion completa.|{"steps":[{"order":1,"action":"solicitar eventos, alertas o incidentes de malware del periodo"},{"order":2,"action":"seleccionar muestra por severidad, tipo de activo y tipo de amenaza"},{"order":3,"action":"validar deteccion, bloqueo o aislamiento, analisis, erradicacion y cierre"},{"order":4,"action":"confirmar si hubo analisis de alcance y verificacion posterior del activo"},{"order":5,"action":"documentar eventos no contenidos, falsos negativos identificados o cierres sin evidencia suficiente"}]}|Alertas EDR o AV, tickets, cronologias, evidencias de aislamiento, analisis, remediacion, reportes de cierre.|Cada caso debe mostrar el flujo completo desde deteccion hasta verificacion posterior.|No basta la herramienta antimalware; importa la respuesta real al evento.|Prueba operativa principal del control contra malware.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b10000001-4a22-4d8f-b001-c1a100000002|5c4d447e-7542-4594-82cf-92dfd8475148|TST-CYB-CTL046-02|Prueba de cobertura y salud operativa del control antimalware|Evaluar si el control antimalware o equivalente cubre efectivamente el universo aplicable y opera sin degradaciones persistentes.|La organizacion evidencia alta cobertura, agentes activos, firmas o capacidades vigentes y tratamiento de excepciones.|Existen activos sin cobertura, agentes inactivos, politicas desactualizadas o brechas sin tratamiento formal.|{"steps":[{"order":1,"action":"obtener universo de activos aplicables al control antimalware"},{"order":2,"action":"comparar universo contra cobertura real de la plataforma"},{"order":3,"action":"seleccionar muestra de activos y validar estado del agente, politicas y vigencia de capacidades"},{"order":4,"action":"revisar eventos de salud o incumplimiento del periodo"},{"order":5,"action":"documentar brechas de cobertura, inactividad o excepciones sin cierre"}]}|Inventario, consola antimalware o EDR, reportes de salud, excepciones, tickets de remediacion.|Debe poder cuantificarse cobertura real y demostrar estado operativo de la proteccion.|Muy alineado con Kiriox: cobertura lineal y punto ciego estructural.|Complementa el test de casos reales con cobertura efectiva.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b10000001-4a22-4d8f-b001-c1a100000003|60039364-b2dc-4216-9c78-92eddda5a328|TST-CYB-CTL047-01|Prueba operativa de deteccion y contencion de phishing|Verificar que la organizacion detecta, bloquea y gestiona correos, enlaces o campañas de phishing relevantes con respuesta trazable.|La muestra evidencia deteccion, bloqueo o neutralizacion, investigacion y acciones de contencion o concientizacion cuando aplica.|Los eventos de phishing pasan sin deteccion suficiente, no se bloquean o no se tratan operativamente.|{"steps":[{"order":1,"action":"solicitar alertas, campañas detectadas o incidentes de phishing del periodo"},{"order":2,"action":"seleccionar muestra por severidad, volumen o impacto"},{"order":3,"action":"validar bloqueo, cuarentena, analisis de alcance, usuarios afectados y remediacion"},{"order":4,"action":"confirmar si hubo tratamiento de cuentas comprometidas o reseteo cuando aplico"},{"order":5,"action":"documentar detecciones tardias, impactos evitables o falta de cierre"}]}|Alertas de correo, SEG, SOAR, tickets, cronologias, reportes de campaña, acciones de contencion.|Cada caso debe incluir origen, accion aplicada, alcance y cierre.|Phishing no se prueba por awareness solo; se prueba por bloqueo y respuesta real.|Prueba operativa del control antiphishing.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b10000001-4a22-4d8f-b001-c1a100000004|60039364-b2dc-4216-9c78-92eddda5a328|TST-CYB-CTL047-02|Prueba de resistencia operativa y aprendizaje frente a phishing|Evaluar si la organizacion usa simulaciones, casos reales o patrones observados para reducir susceptibilidad y mejorar controles.|Las simulaciones o casos revisados generan acciones correctivas, ajustes y reduccion observable o tratamiento de debilidades.|Las simulaciones no producen aprendizaje o los mismos patrones de falla se repiten sin mejora verificable.|{"steps":[{"order":1,"action":"solicitar resultados de simulaciones de phishing o analisis de casos reales del periodo"},{"order":2,"action":"seleccionar muestra por area, criticidad o recurrencia"},{"order":3,"action":"validar resultados, usuarios o grupos expuestos y acciones de mejora aplicadas"},{"order":4,"action":"confirmar si hubo ajustes tecnicos o de proceso ademas de sensibilizacion"},{"order":5,"action":"documentar reincidencia o falta de aprendizaje operativo"}]}|Resultados de simulacion, reportes, acciones correctivas, ajustes de reglas, comunicaciones, seguimientos.|Cada caso debe mostrar hallazgo, accion y validacion posterior.|La mejora real mezcla persona, proceso y filtro técnico.|Muy útil para distinguir cultura de enforcement.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b10000001-4a22-4d8f-b001-c1a100000005|e4372445-23d1-4f66-a850-5c32b9c32b23|TST-CYB-CTL048-01|Prueba operativa de deteccion, priorizacion y remediacion de vulnerabilidades|Verificar que la organizacion identifica vulnerabilidades, las prioriza con criterio de riesgo y ejecuta remediacion dentro de plazos razonables.|La muestra evidencia identificacion, priorizacion, asignacion, remediacion y cierre validado de vulnerabilidades relevantes.|Las vulnerabilidades no se identifican a tiempo, no se priorizan bien o quedan abiertas sin tratamiento verificable.|{"steps":[{"order":1,"action":"solicitar hallazgos de vulnerabilidades del periodo en activos criticos"},{"order":2,"action":"seleccionar muestra por criticidad, explotabilidad, exposicion e impacto"},{"order":3,"action":"validar fecha de deteccion, severidad, priorizacion, asignacion y fecha de remediacion"},{"order":4,"action":"confirmar si hubo validacion posterior al cierre"},{"order":5,"action":"documentar atrasos, cierres sin prueba o vulnerabilidades recurrentes"}]}|Reportes de escaneo, tickets, SLAs, aprobaciones de riesgo, reescaneos, evidencias de cierre.|Cada hallazgo debe mostrar deteccion, priorizacion, accion y validacion posterior.|La gestion madura no es escanear; es cerrar bien y a tiempo.|Prueba operativa central de vulnerabilidades.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b10000001-4a22-4d8f-b001-c1a100000006|e4372445-23d1-4f66-a850-5c32b9c32b23|TST-CYB-CTL048-02|Prueba de cobertura real y excepciones en gestion de vulnerabilidades|Evaluar si el universo relevante de activos esta cubierto por el proceso de vulnerabilidades y si las excepciones se gobiernan formalmente.|La organizacion evidencia cobertura suficiente sobre activos aplicables y excepciones aprobadas, vigentes y con compensacion o plan de cierre.|Existen activos fuera de cobertura, brechas no conocidas o excepciones abiertas sin gobierno adecuado.|{"steps":[{"order":1,"action":"obtener universo de activos sujetos a escaneo o evaluacion de vulnerabilidades"},{"order":2,"action":"comparar cobertura real del proceso contra ese universo"},{"order":3,"action":"identificar activos fuera de cobertura y revisar justificacion"},{"order":4,"action":"muestrear excepciones activas y validar aprobacion, vigencia y compensacion"},{"order":5,"action":"documentar puntos ciegos estructurales o excepciones sin control"}]}|Inventario, herramientas de escaneo, matrices de cobertura, excepciones, aprobaciones, planes de cierre.|Debe poder cuantificarse cobertura y brecha residual con evidencia de excepciones.|Muy alineado con Kiriox: superficie visible versus superficie real.|Complementa la remediacion con cobertura sistémica.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b10000001-4a22-4d8f-b001-c1a100000007|20552b3e-6c1f-444a-aca6-b421c70878f4|TST-CYB-CTL049-01|Prueba operativa de cumplimiento de configuraciones seguras en activos criticos|Verificar que los activos criticos operan con configuraciones seguras definidas y que las desviaciones se detectan y corrigen.|La muestra evidencia conformidad efectiva contra baseline segura o tratamiento formal de desviaciones.|Los activos presentan configuraciones inseguras, deriva persistente o falta de baseline aplicable.|{"steps":[{"order":1,"action":"identificar activos y tecnologias con baseline de configuracion segura definida"},{"order":2,"action":"seleccionar muestra por criticidad y exposicion"},{"order":3,"action":"comparar configuracion efectiva contra baseline segura"},{"order":4,"action":"revisar desviaciones, excepciones y remediaciones del periodo"},{"order":5,"action":"documentar deriva, ausencia de baseline o incumplimientos sin cierre"}]}|Baselines, reportes de compliance, escaneos de configuracion, tickets, excepciones, evidencias de remediacion.|Cada activo muestreado debe tener baseline aplicable y comparacion objetiva de conformidad.|Config segura no es política; es estado técnico verificable.|Prueba fuerte sobre hardening real.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b10000001-4a22-4d8f-b001-c1a100000008|20552b3e-6c1f-444a-aca6-b421c70878f4|TST-CYB-CTL049-02|Prueba de control de deriva y cambios inseguros de configuracion|Evaluar si la organizacion detecta cambios de configuracion no seguros o no autorizados y restaura el estado esperado.|La muestra evidencia deteccion de deriva o cambios inseguros, analisis, correccion y verificacion posterior.|Los cambios inseguros pasan sin detectar, no se revierten o se aceptan informalmente.|{"steps":[{"order":1,"action":"solicitar eventos de deriva, no conformidad o cambios inseguros del periodo"},{"order":2,"action":"seleccionar muestra por criticidad e impacto potencial"},{"order":3,"action":"validar deteccion, causa, autorizacion asociada y accion correctiva"},{"order":4,"action":"confirmar restauracion del estado esperado o excepcion formal aprobada"},{"order":5,"action":"documentar recurrencias o bypass del proceso de configuracion"}]}|Eventos de compliance, tickets de cambio, reportes de deriva, validaciones posteriores, excepciones aprobadas.|Cada caso debe mostrar cambio, desviacion, tratamiento y estado final verificado.|La deriva es una fuga silenciosa de seguridad operacional.|Conecta configuracion segura con cambio y disciplina operativa.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b10000001-4a22-4d8f-b001-c1a100000009|7b7deccd-624e-4809-a902-ce00d0e50a51|TST-CYB-CTL050-01|Prueba operativa de deteccion y contencion de fuga de informacion|Verificar que la organizacion detecta, bloquea o contiene eventos de fuga o intento de fuga de informacion por canales relevantes.|La muestra evidencia deteccion, bloqueo o contencion, investigacion y cierre sobre eventos de fuga o intento de fuga.|Los eventos de fuga no se detectan, no se contienen o no se investiga su alcance real.|{"steps":[{"order":1,"action":"solicitar alertas, bloqueos o casos del periodo relacionados con fuga de informacion"},{"order":2,"action":"seleccionar muestra por severidad, canal y tipo de informacion"},{"order":3,"action":"validar accion de bloqueo o contencion, analisis de alcance, usuarios involucrados y cierre"},{"order":4,"action":"confirmar si hubo remediacion tecnica o correctiva derivada del caso"},{"order":5,"action":"documentar puntos ciegos, canales no cubiertos o cierres sin analisis suficiente"}]}|Alertas DLP, CASB, proxy, correo, tickets, investigaciones, cierres, acciones correctivas.|Cada caso debe mostrar evento, canal, informacion afectada, accion y conclusion.|La fuga se prueba por eventos tratados, no por intención de política.|Prueba operativa principal del control de fuga.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b10000001-4a22-4d8f-b001-c1a100000010|7b7deccd-624e-4809-a902-ce00d0e50a51|TST-CYB-CTL050-02|Prueba de cobertura real de canales de salida y excepciones de fuga|Evaluar si el control de fuga cubre los canales relevantes de salida de informacion y si las excepciones estan gobernadas.|La organizacion evidencia cobertura suficiente de canales relevantes y excepciones formales con vigencia y compensacion.|Existen canales de salida sin cobertura, excepciones abiertas sin control o enforcement parcial no conocido.|{"steps":[{"order":1,"action":"identificar canales relevantes de salida como correo, web, nube, USB, aplicaciones colaborativas y transferencias"},{"order":2,"action":"comparar canales cubiertos por controles contra canales realmente usados por la organizacion"},{"order":3,"action":"muestrear excepciones o grupos excluidos del control"},{"order":4,"action":"validar aprobacion, vigencia, compensacion y riesgo residual de esas excepciones"},{"order":5,"action":"documentar brechas de cobertura o zonas de fuga no controladas"}]}|Matrices de cobertura DLP, configuraciones, inventario de canales, excepciones, aprobaciones, planes de cierre.|Debe poder cuantificarse cobertura y brechas sobre canales de salida reales.|Muy alineado con Kiriox: enforcement lineal y nodos ciegos estructurales.|Complementa el test de casos con cobertura sistémica.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000011|371e6963-53c1-4560-be4f-d47a3d3a6a09|TST-CYB-CTL051-01|Prueba operativa de proteccion de datos sensibles en repositorios y flujos criticos|Verificar que los datos sensibles estan identificados y protegidos operativamente en acceso, almacenamiento, comparticion y uso.|La muestra evidencia protecciones efectivas, restriccion de acceso y tratamiento coherente con la sensibilidad del dato.|Los datos sensibles se encuentran expuestos, sobreretidos, compartidos en exceso o sin protecciones acordes.|{"steps":[{"order":1,"action":"identificar sistemas, repositorios y flujos que contienen datos sensibles"},{"order":2,"action":"seleccionar muestra por criticidad y volumen"},{"order":3,"action":"validar controles de acceso, cifrado, etiquetado, restricciones de comparticion y monitoreo"},{"order":4,"action":"comparar tratamiento real con regla definida para la categoria sensible"},{"order":5,"action":"documentar exposiciones, excesos de acceso o protecciones insuficientes"}]}|Inventarios, etiquetas, ACL, configuraciones, logs, matrices de tratamiento, evidencias DLP o monitoreo.|Cada caso debe mostrar dato sensible real y proteccion efectiva aplicada.|Este control es operativo, no solo taxonómico.|Muy cercano a privacidad, fuga y control de acceso.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000012|371e6963-53c1-4560-be4f-d47a3d3a6a09|TST-CYB-CTL051-02|Prueba de tratamiento de hallazgos o exposiciones sobre datos sensibles|Evaluar si las desviaciones o exposiciones de datos sensibles se corrigen y verifican de forma efectiva.|Los hallazgos revisados muestran contencion, correccion y validacion posterior del cierre.|Los hallazgos quedan abiertos, se corrigen solo en papel o se repiten sin aprendizaje verificable.|{"steps":[{"order":1,"action":"solicitar hallazgos o incidentes del periodo sobre datos sensibles"},{"order":2,"action":"seleccionar muestra por impacto y recurrencia"},{"order":3,"action":"validar contencion, accion correctiva y responsable"},{"order":4,"action":"confirmar verificación posterior del cierre"},{"order":5,"action":"documentar recurrencia, cierres sin prueba o falta de tratamiento suficiente"}]}|Tickets, hallazgos, evidencias de remediacion, validaciones posteriores, cronologias, reportes de cierre.|Cada caso debe mostrar problema, accion y estado final verificado.|El dato sensible mal corregido se convierte en exposición persistente.|Prueba de efectividad sostenida del control.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000013|7d9c2e6c-17c4-4d81-9e94-ddf5c1d2df82|TST-CYB-CTL052-01|Prueba operativa de ejecucion y recuperacion de respaldos|Verificar que los respaldos se ejecutan de forma consistente y que la informacion puede recuperarse efectivamente cuando se requiere.|La muestra evidencia respaldo exitoso, trazable y recuperacion validada sobre datos o sistemas criticos.|Los respaldos fallan sin tratamiento, no cubren el universo critico o no pueden recuperarse en la practica.|{"steps":[{"order":1,"action":"identificar activos, sistemas o datasets criticos cubiertos por respaldo"},{"order":2,"action":"seleccionar muestra de ejecuciones de respaldo y pruebas de restauracion del periodo"},{"order":3,"action":"validar exito de respaldo, errores, tratamiento de fallas y evidencia de restauracion"},{"order":4,"action":"confirmar integridad y usabilidad de la recuperacion realizada"},{"order":5,"action":"documentar fallas recurrentes, falta de prueba o restauraciones incompletas"}]}|Consolas de backup, logs, tickets, pruebas de restauracion, reportes de integridad, cronologias.|Cada caso debe mostrar respaldo ejecutado y al menos evidencia de restauracion o prueba funcional.|Backup sin restauracion probada es fe, no control.|Prueba operativa principal del control de respaldo.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000014|7d9c2e6c-17c4-4d81-9e94-ddf5c1d2df82|TST-CYB-CTL052-02|Prueba de cobertura, retencion y proteccion de respaldos|Evaluar si los respaldos cubren el universo critico, respetan reglas de retencion y permanecen protegidos contra alteracion o borrado indebido.|La organizacion evidencia cobertura suficiente, retencion definida y proteccion de los respaldos frente a alteracion o perdida.|Existen activos criticos sin respaldo, retencion incumplida o respaldos vulnerables a alteracion o borrado no autorizado.|{"steps":[{"order":1,"action":"comparar universo critico de activos o datos con cobertura real de respaldo"},{"order":2,"action":"revisar politicas de retencion y su cumplimiento operativo"},{"order":3,"action":"validar controles de acceso e inmutabilidad o proteccion equivalente sobre los respaldos"},{"order":4,"action":"muestrear excepciones o activos excluidos"},{"order":5,"action":"documentar brechas de cobertura, retencion o proteccion"}]}|Inventario, politicas de backup, matrices de cobertura, configuraciones, controles de acceso, excepciones.|Debe poder cuantificarse cobertura real y demostrar proteccion del repositorio de respaldo.|Muy alineado con Kiriox: cobertura lineal y resiliencia estructural del dato.|Complementa la prueba de restauracion con gobierno del backup.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000015|8033e127-d5c2-4d36-a73a-76b06adfe1a7|TST-CYB-CTL053-01|Prueba operativa de gestion de disponibilidad de servicios criticos|Verificar que los servicios criticos son monitoreados, que las indisponibilidades se atienden y que se restablecen dentro de objetivos definidos o razonables.|La muestra evidencia monitoreo, deteccion, gestion de indisponibilidades y recuperacion verificable de servicios criticos.|Las indisponibilidades no se detectan oportunamente, no se gestionan bien o generan recuperaciones tardias sin aprendizaje posterior.|{"steps":[{"order":1,"action":"identificar servicios criticos y sus mecanismos de monitoreo"},{"order":2,"action":"solicitar incidentes o alertas de disponibilidad del periodo"},{"order":3,"action":"seleccionar muestra por impacto y recurrencia"},{"order":4,"action":"validar deteccion, escalamiento, tratamiento, restablecimiento y comunicacion"},{"order":5,"action":"documentar tiempos excesivos, falta de monitoreo o repeticion sin mejora"}]}|Dashboards, alertas, tickets, cronologias, SLAs, postmortems, reportes de disponibilidad.|Cada caso debe mostrar el evento, el tiempo de deteccion y el restablecimiento logrado.|Disponibilidad se prueba por eventos reales, no por arquitectura declarada.|Control central para servicios y resiliencia operacional.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000016|8033e127-d5c2-4d36-a73a-76b06adfe1a7|TST-CYB-CTL053-02|Prueba de resiliencia y tratamiento de puntos unicos de falla en servicios|Evaluar si los servicios criticos presentan puntos unicos de falla no mitigados o si existen mecanismos efectivos de resiliencia.|La muestra evidencia redundancia, failover o mecanismos equivalentes probados o validados en servicios criticos.|Existen dependencias unicas no cubiertas o mecanismos de resiliencia no probados ni confiables.|{"steps":[{"order":1,"action":"identificar servicios criticos con alta dependencia operacional"},{"order":2,"action":"revisar arquitectura, dependencias y mecanismos de resiliencia declarados"},{"order":3,"action":"seleccionar muestra de eventos, pruebas o fallas que hayan ejercitado la resiliencia"},{"order":4,"action":"validar si el mecanismo funciono en la practica o si aparecieron puntos unicos de falla"},{"order":5,"action":"documentar fragilidades estructurales o resiliencia solo declarativa"}]}|Diagramas, inventarios de dependencias, pruebas de failover, incidentes, reportes técnicos, postmortems.|Debe existir evidencia de funcionamiento real o validado de la resiliencia declarada.|Muy alineado con Kiriox: aquí aparece el nodo crítico y el efecto cascada.|Prueba puente entre disponibilidad lineal y fragilidad estructural.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000017|0c0e8473-bbab-412b-bb57-6adc262d1ee2|TST-CYB-CTL054-01|Prueba operativa de monitoreo y gestion de capacidad y rendimiento|Verificar que la organizacion monitorea capacidad y rendimiento, detecta saturaciones y actua antes de degradaciones severas del servicio.|La muestra evidencia monitoreo activo, alertas utiles, analisis de tendencia y acciones preventivas o correctivas ejecutadas.|La capacidad o el rendimiento se gestionan reactivamente, sin monitoreo suficiente o sin accion oportuna ante saturacion.|{"steps":[{"order":1,"action":"identificar servicios, plataformas o componentes donde capacidad y rendimiento sean criticos"},{"order":2,"action":"solicitar alertas, reportes de tendencia e incidentes del periodo"},{"order":3,"action":"seleccionar muestra por impacto, recurrencia o cercania a umbrales"},{"order":4,"action":"validar si hubo deteccion, analisis, ajuste de capacidad o tuning antes o despues del evento"},{"order":5,"action":"documentar saturaciones previsibles no gestionadas o acciones tardias"}]}|Dashboards, alertas, reportes de tendencia, tickets, capacity plans, postmortems.|Cada caso debe mostrar indicador, umbral, evento y accion aplicada.|Capacidad mal gestionada es fragilidad incubada, no solo problema técnico.|Prueba operativa de prevención de degradación.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000018|0c0e8473-bbab-412b-bb57-6adc262d1ee2|TST-CYB-CTL054-02|Prueba de aprendizaje y ajuste estructural ante eventos de capacidad|Evaluar si la organizacion usa incidentes o alertas de capacidad para ajustar arquitectura, umbrales o patrones operativos y reducir recurrencia.|Los eventos revisados generaron cambios estructurales, tuning o ampliacion efectiva y muestran mejora posterior.|Los mismos cuellos de botella reaparecen sin correccion estructural o solo se resuelven temporalmente.|{"steps":[{"order":1,"action":"seleccionar incidentes o alertas significativas de capacidad del periodo"},{"order":2,"action":"validar si hubo RCA, plan de ajuste o reconfiguracion estructural"},{"order":3,"action":"confirmar implementacion de la mejora y medicion posterior"},{"order":4,"action":"comparar ocurrencias antes y despues del ajuste"},{"order":5,"action":"documentar parches reactivos o recurrencia sin aprendizaje"}]}|RCA, tickets, cambios, capacity plans, métricas antes y después, postmortems.|Cada caso debe mostrar evento, mejora aplicada y verificación posterior.|Aquí se distingue apagar incendios de gobernar capacidad.|Conecta rendimiento con madurez operativa real.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000019|8b5806fc-741e-47cc-a435-add9ac35ac2d|TST-CYB-CTL055-01|Prueba operativa de trazabilidad de eventos y acciones criticas|Verificar que las acciones y eventos criticos sobre sistemas o procesos relevantes quedan trazados con suficiente detalle para reconstruccion y atribucion.|La muestra evidencia registros completos, atribuibles, consistentes y utilizables para reconstruir acciones criticas.|Los eventos no son trazables, carecen de actor claro o no permiten reconstruccion razonable.|{"steps":[{"order":1,"action":"identificar acciones y eventos criticos que deben quedar trazados"},{"order":2,"action":"seleccionar muestra de eventos de administracion, cambios, acceso o transacciones sensibles"},{"order":3,"action":"validar presencia de usuario, fecha, activo, accion y resultado"},{"order":4,"action":"revisar si se puede correlacionar el evento con su contexto operativo"},{"order":5,"action":"documentar lagunas de trazabilidad, ambiguedad o registros insuficientes"}]}|Logs, SIEM, auditorias de aplicaciones, registros de cambios, historiales operativos.|Cada evento muestreado debe permitir atribucion y reconstruccion razonable.|Sin trazabilidad no hay control defendible ni auditoría útil.|Prueba base para investigación y auditabilidad.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b11000001-4a22-4d8f-b001-c1a100000020|8b5806fc-741e-47cc-a435-add9ac35ac2d|TST-CYB-CTL055-02|Prueba de completitud y consistencia de trazabilidad entre sistemas|Evaluar si la trazabilidad se conserva de extremo a extremo cuando una operacion atraviesa multiples sistemas o capas tecnicas.|La muestra evidencia correlacion razonable entre sistemas fuente, intermedios y destino sobre operaciones criticas.|La trazabilidad se pierde entre capas, no puede correlacionarse o presenta huecos materiales.|{"steps":[{"order":1,"action":"seleccionar procesos o transacciones que recorran multiples sistemas"},{"order":2,"action":"identificar eventos esperados en cada punto del recorrido"},{"order":3,"action":"muestrear casos reales y correlacionar identificadores, tiempos y acciones entre sistemas"},{"order":4,"action":"validar continuidad de la huella operativa de extremo a extremo"},{"order":5,"action":"documentar quiebres de correlacion o puntos ciegos"}]}|Logs de aplicaciones, middleware, bases, SIEM, trazas, identificadores de transacción.|Cada caso debe demostrar correlación entre varios sistemas implicados.|Muy útil para Kiriox porque detecta pérdida de trazabilidad en relaciones N:M reales.|Prueba avanzada de auditabilidad operativa.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000021|0dc4f9bf-0073-43c1-8129-a4a63dc3881c|TST-CYB-CTL056-01|Prueba operativa de deteccion y tratamiento de anomalias relevantes|Verificar que la organizacion detecta anomalias operativas o de seguridad relevantes y las investiga hasta conclusion razonada.|La muestra evidencia deteccion de anomalias, analisis suficiente, clasificacion y cierre con accion o descarte justificado.|Las anomalias no se detectan, no se investigan o se cierran de forma superficial.|{"steps":[{"order":1,"action":"solicitar alertas o casos del periodo etiquetados como anomalias o comportamiento anomalo"},{"order":2,"action":"seleccionar muestra por criticidad, recurrencia o impacto potencial"},{"order":3,"action":"validar triage, investigacion, conclusion y accion aplicada o descarte"},{"order":4,"action":"confirmar si hubo escalamiento a incidente o ajuste del modelo o regla"},{"order":5,"action":"documentar anomalias ignoradas, mal clasificadas o mal cerradas"}]}|Alertas SIEM o UEBA, tickets, investigaciones, cierres, ajustes de reglas o modelos.|Cada caso debe mostrar deteccion, razonamiento y decisión trazable.|Anomalía sin investigación útil es ruido, no control.|Prueba operativa del control de detección avanzada.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000022|0dc4f9bf-0073-43c1-8129-a4a63dc3881c|TST-CYB-CTL056-02|Prueba de mejora del modelo de deteccion a partir de anomalias|Evaluar si la organizacion usa anomalias reales para ajustar reglas, casos de uso o parametros y mejorar sensibilidad o precision.|Las anomalias revisadas generaron ajuste de reglas, enriquecimiento o cambios verificables en el modelo de deteccion.|La organizacion observa anomalias pero no aprende ni ajusta su capacidad de deteccion.|{"steps":[{"order":1,"action":"seleccionar anomalias relevantes del periodo con aprendizaje potencial"},{"order":2,"action":"validar si hubo ajuste de regla, umbral, fuente o caso de uso derivado del analisis"},{"order":3,"action":"confirmar implementacion y fecha del ajuste"},{"order":4,"action":"revisar si mejoro la deteccion o redujo ruido en eventos posteriores"},{"order":5,"action":"documentar ausencia de aprendizaje operativo"}]}|Cambios de reglas, casos de uso, ajustes de umbral, postmortems, métricas de efectividad.|Debe existir trazabilidad entre anomalía observada y mejora implementada.|Muy útil para medir madurez del SOC o monitoreo avanzado.|Conecta detección con aprendizaje real del sistema.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000023|860cac58-6008-407e-aaec-9739048300c1|TST-CYB-CTL057-01|Prueba operativa de sincronizacion temporal consistente en registros criticos|Verificar que los sistemas criticos mantienen referencias temporales coherentes que permiten correlacionar eventos y reconstruir cronologias confiables.|La muestra evidencia sincronizacion consistente y diferencias temporales dentro de tolerancias definidas o razonables.|Los sistemas presentan desalineaciones temporales relevantes que afectan correlacion e investigacion.|{"steps":[{"order":1,"action":"identificar sistemas y fuentes de log criticas para correlacion de eventos"},{"order":2,"action":"seleccionar muestra de sistemas por criticidad y heterogeneidad tecnica"},{"order":3,"action":"comparar referencias temporales, configuraciones y eventos correlacionables"},{"order":4,"action":"validar uso de fuentes de tiempo y evidencia de salud o sincronizacion"},{"order":5,"action":"documentar desviaciones temporales materiales o falta de control"}]}|Configuraciones NTP o equivalentes, logs, eventos correlacionados, evidencias de monitoreo de tiempo.|La muestra debe demostrar coherencia temporal suficiente para investigación y trazabilidad.|Tiempo inconsistente destruye evidencia aunque existan logs.|Prueba base para forense y correlación sistémica.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000024|860cac58-6008-407e-aaec-9739048300c1|TST-CYB-CTL057-02|Prueba de tratamiento de desincronizaciones temporales relevantes|Evaluar si la organizacion detecta y corrige oportunamente desviaciones de tiempo que afecten monitoreo, trazabilidad o integridad de registros.|Los casos revisados muestran deteccion, correccion y validacion posterior de desincronizaciones relevantes.|Las desviaciones no se detectan, no se corrigen o reaparecen sin aprendizaje ni cierre suficiente.|{"steps":[{"order":1,"action":"solicitar alertas, hallazgos o incidentes del periodo sobre desincronizacion temporal"},{"order":2,"action":"seleccionar muestra por impacto y recurrencia"},{"order":3,"action":"validar deteccion, diagnostico, correccion y fecha de restablecimiento"},{"order":4,"action":"confirmar verificación posterior de la sincronizacion"},{"order":5,"action":"documentar recurrencias o cierres sin prueba"}]}|Alertas, tickets, configuraciones, verificaciones posteriores, cronologias, postmortems.|Cada caso debe mostrar problema, corrección y estado final comprobado.|No basta configurar NTP una vez; importa la disciplina sostenida.|Complementa la prueba de coherencia temporal con respuesta real.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000025|7d827e19-b18d-44fc-a71e-ba8da5752055|TST-CYB-CTL058-01|Prueba operativa de deteccion y control de bypass de controles|Verificar que la organizacion identifica intentos, rutas o prácticas que eluden controles establecidos y que las corrige de forma efectiva.|La muestra evidencia deteccion de bypass o excepciones indebidas, investigacion y cierre con remediacion verificable.|Existen rutas paralelas, excepciones informales o bypass conocidos sin tratamiento suficiente.|{"steps":[{"order":1,"action":"identificar controles criticos susceptibles de bypass como autenticacion, aprobaciones, monitoreo, cambios, DLP o segregacion"},{"order":2,"action":"solicitar hallazgos, excepciones, incidentes o revisiones del periodo relacionados con bypass"},{"order":3,"action":"seleccionar muestra por criticidad y recurrencia"},{"order":4,"action":"validar deteccion, causa, impacto y accion correctiva"},{"order":5,"action":"documentar bypass persistente, excepciones informales o rutas paralelas no gobernadas"}]}|Hallazgos, excepciones, incidentes, tickets, revisiones de proceso, evidencias de remediacion.|Cada caso debe mostrar la ruta de bypass, el control afectado y la corrección aplicada.|Control estructuralmente crítico porque el bypass destruye confianza sistémica.|Muy alineado con Kiriox: hard gates, dependencia y ruptura real.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000026|7d827e19-b18d-44fc-a71e-ba8da5752055|TST-CYB-CTL058-02|Prueba de gobernanza de excepciones para evitar bypass institucionalizado|Evaluar si las excepciones a controles criticos se aprueban, limitan, monitorean y cierran sin convertirse en bypass permanente.|Las excepciones revisadas tienen aprobacion formal, plazo, compensacion y cierre o renovacion justificada.|Las excepciones operan como bypass permanente, sin plazo, sin compensacion o sin monitoreo real.|{"steps":[{"order":1,"action":"solicitar registro de excepciones a controles criticos"},{"order":2,"action":"seleccionar muestra por impacto y antiguedad"},{"order":3,"action":"validar aprobacion, justificacion, compensacion, plazo y monitoreo"},{"order":4,"action":"confirmar si la excepcion fue cerrada, renovada o eliminada con criterio formal"},{"order":5,"action":"documentar excepciones envejecidas, abiertas o sin compensacion suficiente"}]}|Registro de excepciones, aprobaciones, compensaciones, monitoreo, cierres, renovaciones.|Cada excepción debe ser trazable y finita o formalmente reevaluada.|La excepción sin disciplina es bypass legitimado.|Complementa el test de bypass con gobierno formal.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000027|8c29f0f5-a350-47c0-b058-7018038f5284|TST-CYB-CTL059-01|Prueba operativa de control de software autorizado en endpoints y servidores|Verificar que solo software autorizado o permitido se encuentra instalado o ejecutandose en activos relevantes, y que las desviaciones se detectan y corrigen.|La muestra evidencia universo de software gobernado, deteccion de no autorizado y remediacion verificable.|Existen aplicaciones no autorizadas, desconocidas o no gobernadas sin tratamiento suficiente.|{"steps":[{"order":1,"action":"obtener inventario de software permitido, bloqueado o gobernado"},{"order":2,"action":"seleccionar muestra de endpoints y servidores por criticidad"},{"order":3,"action":"comparar software instalado o ejecutado contra el universo autorizado"},{"order":4,"action":"revisar hallazgos o eventos de software no autorizado del periodo"},{"order":5,"action":"documentar aplicaciones no autorizadas, sin owner o sin tratamiento"}]}|Inventario de software, allowlists, EDR, herramientas de descubrimiento, tickets, acciones correctivas.|Cada activo muestreado debe permitir comparar software real versus software autorizado.|Software no autorizado es superficie de ataque y bypass operativo.|Prueba operativa del control de software.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000028|8c29f0f5-a350-47c0-b058-7018038f5284|TST-CYB-CTL059-02|Prueba de tratamiento de software no autorizado o riesgoso|Evaluar si la organizacion elimina, bloquea o regulariza oportunamente software no autorizado o de alto riesgo identificado.|Los casos revisados muestran deteccion, analisis, remocion, bloqueo o formalizacion controlada del software identificado.|El software riesgoso permanece activo, se regulariza informalmente o se repite sin aprendizaje ni enforcement.|{"steps":[{"order":1,"action":"solicitar eventos o hallazgos del periodo asociados a software no autorizado o riesgoso"},{"order":2,"action":"seleccionar muestra por criticidad e impacto potencial"},{"order":3,"action":"validar analisis, decision, remocion, bloqueo o excepcion formal aprobada"},{"order":4,"action":"confirmar estado final del activo afectado"},{"order":5,"action":"documentar recurrencias, tolerancia informal o ausencia de enforcement"}]}|Hallazgos, tickets, bloqueos, remociones, excepciones, verificaciones posteriores.|Cada caso debe mostrar el antes, la acción y el estado final comprobado.|Muy útil para separar catálogo de software de enforcement real.|Complementa la cobertura con remediación efectiva.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000029|1dc3f6e6-52ff-4254-8c1a-e8b0c9139b4f|TST-CYB-CTL060-01|Prueba operativa de seguridad de red en controles perimetrales y segmentacion basica|Verificar que la red opera con controles efectivos de filtrado, restriccion, segmentacion basica y exposicion minimizada según criticidad.|La muestra evidencia reglas efectivas, puertos y flujos justificados, segmentacion aplicada y exposicion controlada.|Existen reglas excesivas, puertos abiertos innecesarios, segmentacion débil o exposicion no justificada.|{"steps":[{"order":1,"action":"identificar segmentos, dispositivos y flujos criticos de red"},{"order":2,"action":"seleccionar muestra de reglas, aperturas, segmentos y activos expuestos"},{"order":3,"action":"validar necesidad de negocio, justificacion, owner y configuracion efectiva"},{"order":4,"action":"revisar eventos, hallazgos o cambios del periodo sobre seguridad de red"},{"order":5,"action":"documentar reglas amplias, aperturas antiguas o segmentacion insuficiente"}]}|Reglas de firewall, inventarios de red, diagramas, tickets de cambio, hallazgos, escaneos, ownership de reglas.|Cada caso debe mostrar regla o flujo, justificación y configuración efectiva.|Red segura no es solo firewall; es exposición mínima y disciplina de reglas.|Prueba operativa de control de red básico.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b12000001-4a22-4d8f-b001-c1a100000030|1dc3f6e6-52ff-4254-8c1a-e8b0c9139b4f|TST-CYB-CTL060-02|Prueba de monitoreo y tratamiento de eventos relevantes de seguridad de red|Evaluar si la organizacion detecta, investiga y corrige eventos relevantes observados en la red.|La muestra evidencia alertas o eventos de red analizados, concluidos y tratados con trazabilidad suficiente.|Los eventos de red no se investigan, se cierran superficialmente o no producen remediacion cuando corresponde.|{"steps":[{"order":1,"action":"solicitar eventos, alertas o incidentes del periodo relacionados con seguridad de red"},{"order":2,"action":"seleccionar muestra por severidad, recurrencia o impacto"},{"order":3,"action":"validar triage, investigacion, conclusion y accion correctiva o de contencion"},{"order":4,"action":"confirmar si hubo ajuste de regla, bloqueo, segmentacion o medida posterior"},{"order":5,"action":"documentar falta de analisis, ruido excesivo o ausencia de remediacion"}]}|Alertas IDS o IPS, SIEM, tickets, cronologias, cambios de regla, bloqueos, reportes de cierre.|Cada caso debe mostrar evento, razonamiento y acción aplicada.|Complementa configuración estática con capacidad real de defensa de red.|Prueba operativa del plano de monitoreo y respuesta de red.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
\.

with normalized as (
  select
    (
      case
        when length(split_part(id, '-', 1)) > 8 then
          left(split_part(id, '-', 1), 8) || '-' || split_part(id, '-', 2) || '-' || split_part(id, '-', 3) || '-' || split_part(id, '-', 4) || '-' || split_part(id, '-', 5)
        else id
      end
    ) as id_norm,
    control_id,
    code,
    title,
    evaluation_guidance,
    pass_criteria,
    fail_criteria,
    evaluator_steps,
    evidence_required,
    evidence_min_spec,
    sample_guidance,
    notes,
    status,
    is_active,
    framework_version_id,
    effective_from,
    effective_to,
    created_at,
    updated_at
  from tmp_cyb_group_10_12
),
ins as (
  insert into core.control_evaluation_catalog (
    id,
    control_id,
    dimension_id,
    code,
    title,
    evaluation_guidance,
    pass_criteria,
    fail_criteria,
    evaluator_steps,
    evidence_required,
    evidence_min_spec,
    sample_guidance,
    notes,
    status,
    is_active,
    framework_version_id,
    effective_from,
    effective_to,
    created_at,
    updated_at
  )
  select
    n.id_norm::uuid,
    n.control_id::uuid,
    'c288a358-ef38-4c64-960b-43fffb9a3412'::uuid,
    n.code,
    n.title,
    n.evaluation_guidance,
    n.pass_criteria,
    n.fail_criteria,
    n.evaluator_steps::jsonb,
    n.evidence_required,
    n.evidence_min_spec,
    n.sample_guidance,
    n.notes,
    n.status,
    n.is_active::boolean,
    n.framework_version_id::uuid,
    n.effective_from::timestamptz,
    n.effective_to::timestamptz,
    n.created_at::timestamptz,
    n.updated_at::timestamptz
  from normalized n
  where not exists (
    select 1
    from core.control_evaluation_catalog c
    where c.id = n.id_norm::uuid
       or c.code = n.code
  )
  returning 1
)
select count(*) as inserted_rows
from ins;

commit;

