begin;

drop table if exists xdata.backup_control_eval_before_cyb_insert_batch8_9_20260329;
create table xdata.backup_control_eval_before_cyb_insert_batch8_9_20260329 as
select *
from core.control_evaluation_catalog;

create temp table tmp_cyb_group_8_9 (
  id text,
  control_id text,
  code text,
  title text,
  evaluation_guidance text,
  pass_criteria text,
  fail_criteria text,
  evaluator_steps text,
  evidence_required text,
  evidence_min_spec text,
  sample_guidance text,
  notes text,
  status text,
  is_active text,
  framework_version_id text,
  effective_from text,
  effective_to text,
  created_at text,
  updated_at text
);

copy tmp_cyb_group_8_9
from stdin
with (format text, delimiter '|', null 'NULL');
b8000001-4a22-4d8f-b001-c1a100000001|e8ec2ae5-316e-4ad3-85fa-dea94b885ac0|TST-CYB-CTL036-01|Prueba operativa de restriccion de acceso fisico a areas criticas|Verificar que el acceso fisico a areas criticas se encuentra restringido, trazado y alineado a necesidad operativa real.|La muestra evidencia acceso limitado a personal autorizado, registros de ingreso consistentes y ausencia de accesos no justificados.|Existen ingresos no autorizados, registros incompletos o areas criticas con acceso fisico excesivamente abierto.|{"steps":[{"order":1,"action":"identificar areas fisicas criticas como datacenter, cuartos de comunicaciones, NOC, SOC, archivos sensibles y zonas de equipos"},{"order":2,"action":"solicitar listados de autorizados, registros de ingreso y mecanismos de control de acceso"},{"order":3,"action":"seleccionar muestra de ingresos y usuarios autorizados por criticidad"},{"order":4,"action":"validar correspondencia entre autorizacion, necesidad operativa y acceso efectivamente registrado"},{"order":5,"action":"documentar accesos no justificados, comparticion de credenciales o falta de trazabilidad"}]}|Listas de acceso autorizado, logs de ingreso, registros de visitantes, CCTV si aplica, aprobaciones, bitacoras fisicas.|Cada caso debe permitir validar quien ingreso, cuando, con que autorizacion y a que area.|No basta el lector de tarjetas; importa el control real del acceso.|Control fisico base para nodos de alta criticidad.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b8000001-4a22-4d8f-b001-c1a100000002|e8ec2ae5-316e-4ad3-85fa-dea94b885ac0|TST-CYB-CTL036-02|Prueba de gestion operativa de visitantes en zonas sensibles|Evaluar si los visitantes, contratistas o terceros son controlados, acompañados y registrados cuando ingresan a zonas sensibles.|Los ingresos de visitantes revisados muestran autorizacion previa, identificacion, acompanamiento y registro de salida.|Los visitantes ingresan sin control suficiente, sin acompanamiento o sin trazabilidad completa.|{"steps":[{"order":1,"action":"solicitar registros de visitantes y procedimiento aplicable a zonas sensibles"},{"order":2,"action":"seleccionar muestra de ingresos de visitantes o contratistas"},{"order":3,"action":"validar autorizacion, identificacion, acompanamiento y salida registrada"},{"order":4,"action":"confirmar si el alcance del acceso fue limitado al area necesaria"},{"order":5,"action":"documentar ingresos sin control o sin cierre de registro"}]}|Registros de visitantes, aprobaciones, identificaciones, bitacoras de acompanamiento, CCTV si existe.|Cada caso debe incluir ingreso, responsable anfitrion, area visitada y salida.|Muy util para detectar brechas reales en seguridad fisica cotidiana.|Prueba operativa sobre terceros fisicos en zonas sensibles.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b8000001-4a22-4d8f-b001-c1a100000003|0f3b95ce-2da5-43a5-9686-c5b157554469|TST-CYB-CTL037-01|Prueba operativa de control y respuesta ante robo o extravio fisico de activos|Verificar que la organizacion detecta, reporta y gestiona oportunamente eventos de robo o extravio fisico de activos.|Los casos revisados muestran deteccion, reporte, evaluacion de impacto, contencion y cierre formal.|Los eventos no se reportan a tiempo, no se contiene el riesgo o no existe evaluacion de impacto suficiente.|{"steps":[{"order":1,"action":"solicitar casos del periodo relacionados con robo o extravio fisico de activos"},{"order":2,"action":"seleccionar muestra por tipo de activo e impacto"},{"order":3,"action":"validar tiempo de reporte, acciones de contencion y analisis de exposicion"},{"order":4,"action":"confirmar medidas aplicadas como bloqueo, revocacion, wipe remoto o denuncia interna"},{"order":5,"action":"documentar casos sin tratamiento completo o con respuesta tardia"}]}|Tickets, reportes de perdida, actas, evidencias de bloqueo o wipe, evaluaciones de impacto, cierres.|Cada caso debe mostrar evento, reporte, medidas aplicadas y conclusion final.|El robo fisico se vuelve incidente mayor cuando no hay respuesta tecnica oportuna.|Conecta activo fisico con identidad, datos y continuidad.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b8000001-4a22-4d8f-b001-c1a100000004|0f3b95ce-2da5-43a5-9686-c5b157554469|TST-CYB-CTL037-02|Prueba de controles preventivos contra sustraccion fisica de activos|Evaluar si existen barreras reales para prevenir sustraccion fisica de equipos o medios sensibles.|La muestra evidencia controles como anclaje, custodia, monitoreo, inventario trazable y restricciones de retiro aplicados en la practica.|Los activos pueden retirarse o desaparecer sin barreras suficientes o sin trazabilidad de custodia.|{"steps":[{"order":1,"action":"identificar activos fisicos con mayor riesgo de sustraccion como laptops, medios removibles, equipos de red y dispositivos moviles"},{"order":2,"action":"revisar barreras preventivas aplicables por tipo de activo"},{"order":3,"action":"seleccionar muestra de activos y validar custodia, ubicacion y condiciones de retiro"},{"order":4,"action":"comprobar si el retiro o traslado requiere autorizacion y queda registrado"},{"order":5,"action":"documentar debilidades preventivas o ausencia de trazabilidad"}]}|Inventario, actas de entrega, registros de salida, controles de custodia, CCTV o controles de zona si aplican.|La muestra debe demostrar barreras reales frente a retiro no autorizado.|No basta saber que existe el activo; importa impedir su sustraccion silenciosa.|Prueba preventiva complementaria al tratamiento del evento.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b8000001-4a22-4d8f-b001-c1a100000005|b0b4fd2c-a4d3-4705-b346-ce92480a48e2|TST-CYB-CTL038-01|Prueba operativa de proteccion fisica de infraestructura critica|Verificar que la infraestructura fisica critica cuenta con protecciones reales frente a acceso, daño, manipulación o interrupcion.|La muestra evidencia controles fisicos efectivos y estado operativo adecuado sobre infraestructura critica.|Existen protecciones ausentes, degradadas o no funcionales en infraestructura critica.|{"steps":[{"order":1,"action":"identificar infraestructura fisica critica como cuartos de telecomunicaciones, racks, energia, climatizacion, UPS, generadores y sensores relevantes"},{"order":2,"action":"seleccionar muestra por criticidad y dependencia operacional"},{"order":3,"action":"validar barreras fisicas, condiciones ambientales, monitoreo y mantenimiento visible"},{"order":4,"action":"confirmar si hay evidencia de alarmas, inspecciones o revisiones periodicas"},{"order":5,"action":"documentar protecciones faltantes, deterioradas o inoperantes"}]}|Inventarios de infraestructura, checklists de inspeccion, registros de mantenimiento, sensores, alarmas, evidencias fotograficas.|Cada elemento muestreado debe mostrar su proteccion y estado operativo verificable.|Esta prueba baja la infraestructura de la teoria al estado fisico real.|Muy importante para continuidad y nodos raiz del sistema.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b8000001-4a22-4d8f-b001-c1a100000006|b0b4fd2c-a4d3-4705-b346-ce92480a48e2|TST-CYB-CTL038-02|Prueba de gestion de fallas o degradaciones en infraestructura fisica|Evaluar si la organizacion detecta y corrige fallas o degradaciones en infraestructura fisica antes de que afecten el servicio o la seguridad.|Las fallas o degradaciones revisadas fueron detectadas, registradas, corregidas y verificadas en tiempo razonable.|Las fallas permanecen abiertas, se corrigen tarde o no se verifica su resolucion real.|{"steps":[{"order":1,"action":"solicitar incidentes, alertas o mantenimientos correctivos sobre infraestructura fisica del periodo"},{"order":2,"action":"seleccionar muestra por impacto y tipo de componente"},{"order":3,"action":"validar deteccion, registro, responsable, correccion y fecha de cierre"},{"order":4,"action":"confirmar si la resolucion fue probada o verificada despues del arreglo"},{"order":5,"action":"documentar recurrencias, cierres sin prueba o degradaciones persistentes"}]}|Tickets, alertas, bitacoras de mantenimiento, verificaciones post correccion, reportes de incidente.|Cada caso debe incluir falla, tratamiento y verificacion posterior.|Infraestructura sin capacidad de correccion temprana concentra fragilidad fisica.|Prueba de operacion sostenida del control fisico.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b8000001-4a22-4d8f-b001-c1a100000007|5a41574e-9a1b-491c-9fe8-18119b1fbc3f|TST-CYB-CTL039-01|Prueba operativa de proteccion visual de informacion en entornos de trabajo|Verificar que la informacion sensible no queda expuesta visualmente en puestos de trabajo, salas, pantallas o material impreso.|La muestra evidencia ausencia de exposicion visual indebida y aplicacion real de medidas de proteccion visual.|Se observan pantallas abiertas, impresos expuestos, pizarras visibles o informacion sensible observable por terceros no autorizados.|{"steps":[{"order":1,"action":"identificar areas de trabajo, salas, recepciones y zonas compartidas donde exista riesgo de exposicion visual"},{"order":2,"action":"realizar observacion controlada o revisar hallazgos documentados del periodo"},{"order":3,"action":"seleccionar muestra de puestos, salas o practicas operativas"},{"order":4,"action":"validar bloqueo de pantalla, resguardo de impresos, ubicacion de monitores y manejo de informacion visible"},{"order":5,"action":"documentar exposiciones indebidas o incumplimientos repetitivos"}]}|Hallazgos de inspeccion, recorridos, checklists, evidencias fotograficas controladas si aplica, tickets correctivos.|La muestra debe basarse en observacion directa o hallazgos recientes verificables.|Control simple, pero altamente revelador de disciplina operativa real.|Muy util para cultura operativa y proteccion cotidiana del dato.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b8000001-4a22-4d8f-b001-c1a100000008|5a41574e-9a1b-491c-9fe8-18119b1fbc3f|TST-CYB-CTL039-02|Prueba de disciplina operativa sobre bloqueo y resguardo visual|Evaluar si los usuarios aplican de forma consistente bloqueo de pantalla y resguardo visual de informacion al ausentarse o trabajar en espacios compartidos.|La muestra evidencia comportamiento consistente de bloqueo, resguardo y no exposicion visual en escenarios reales.|Los usuarios dejan sesiones abiertas o informacion visible sin resguardo en ausencia o en espacios compartidos.|{"steps":[{"order":1,"action":"definir poblaciones y entornos de mayor riesgo visual"},{"order":2,"action":"realizar validaciones por observacion controlada, revisiones de hallazgos o ejercicios autorizados"},{"order":3,"action":"evaluar uso de bloqueo automatico y practica real del usuario"},{"order":4,"action":"revisar reincidencias o tratamientos aplicados por incumplimiento"},{"order":5,"action":"documentar patron de incumplimiento o ausencia de enforcement"}]}|Configuraciones de bloqueo, hallazgos de observacion, bitacoras de inspeccion, acciones correctivas o disciplinarias.|Debe poder demostrarse tanto el control tecnico como el comportamiento observable.|Cuando el control visual falla, la fuga ocurre sin log tecnico.|Prueba muy util para enlazar cultura y seguridad real.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b8000001-4a22-4d8f-b001-c1a100000009|9d1e2f99-a188-4d2e-be32-5773dc5e6758|TST-CYB-CTL040-01|Prueba operativa de seguridad fisica de dispositivos corporativos|Verificar que los dispositivos fisicos corporativos se encuentran bajo controles efectivos de custodia, configuracion fisica y uso seguro.|La muestra evidencia dispositivos bajo custodia trazable, con configuraciones basicas de seguridad fisica y uso controlado.|Existen dispositivos sin custodia clara, sin protecciones basicas o con uso fisico inseguro recurrente.|{"steps":[{"order":1,"action":"identificar tipos de dispositivos fisicos relevantes como laptops, moviles, tokens, equipos de red y estaciones de trabajo especiales"},{"order":2,"action":"seleccionar muestra por movilidad, criticidad y sensibilidad del uso"},{"order":3,"action":"validar asignacion, custodia, ubicacion y controles fisicos o de arranque aplicables"},{"order":4,"action":"revisar hallazgos o eventos de uso fisico inseguro del periodo"},{"order":5,"action":"documentar ausencia de custodia, controles fisicos insuficientes o malas practicas"}]}|Inventario, actas de entrega, configuraciones de arranque o bloqueo, reportes MDM o EDR, hallazgos de inspeccion.|Cada dispositivo muestreado debe tener owner o custodio y controles fisicos verificables.|Dispositivo fisico inseguro suele ser puerta de entrada a compromiso logico.|Conecta endpoint con seguridad fisica real.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b8000001-4a22-4d8f-b001-c1a100000010|9d1e2f99-a188-4d2e-be32-5773dc5e6758|TST-CYB-CTL040-02|Prueba de tratamiento de incidentes asociados a dispositivos fisicos|Evaluar si la organizacion detecta y corrige incidentes vinculados a manipulacion, perdida, alteracion o uso fisico indebido de dispositivos.|Los casos revisados muestran deteccion, tratamiento, evaluacion de impacto y cierre verificable.|Los incidentes sobre dispositivos quedan subgestionados, sin contencion suficiente o sin aprendizaje posterior.|{"steps":[{"order":1,"action":"solicitar incidentes del periodo asociados a dispositivos fisicos"},{"order":2,"action":"seleccionar muestra por impacto y tipo de dispositivo"},{"order":3,"action":"validar deteccion, contencion, analisis y acciones correctivas"},{"order":4,"action":"confirmar cierre formal y medidas para evitar repeticion"},{"order":5,"action":"documentar vacios de respuesta o recurrencia del problema"}]}|Tickets, incidentes, bitacoras, acciones correctivas, bloqueos, evaluaciones de impacto, cierres.|Cada caso debe mostrar respuesta integral y no solo registro del evento.|Permite separar custodia declarada de control realmente ejercido.|Prueba operacional complementaria al control preventivo del dispositivo.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000011|9fbd7b15-802f-4638-90d7-04b92c52a59b|TST-CYB-CTL041-01|Prueba operativa de continuidad de servicios de soporte criticos|Verificar que los servicios de soporte criticos pueden mantenerse o restablecerse sin quiebres inadmisibles ante fallas, ausencias o interrupciones.|La muestra evidencia cobertura de soporte, reemplazo funcional, escalamiento y continuidad efectiva durante eventos relevantes.|Los servicios de soporte se interrumpen por ausencia de personas, proveedores o capacidad sin respuesta adecuada.|{"steps":[{"order":1,"action":"identificar servicios de soporte criticos para operacion, seguridad y continuidad"},{"order":2,"action":"seleccionar eventos, ausencias, fallas o pruebas del periodo que hayan tensionado la capacidad de soporte"},{"order":3,"action":"validar disponibilidad de reemplazo, escalamiento, acuerdos y tiempos reales de respuesta"},{"order":4,"action":"confirmar si el servicio se mantuvo o recupero dentro de umbrales definidos"},{"order":5,"action":"documentar dependencias no cubiertas, sobrecarga o interrupciones sin contencion"}]}|Acuerdos de soporte, turnos, on-call, tickets, escalaciones, reportes de capacidad, incidentes, evidencias de continuidad.|Cada caso debe mostrar el evento y como se sostuvo o recupero el soporte critico.|Soporte critico caido puede romper controles que en papel existen.|Prueba muy relevante para resiliencia operacional.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000012|9fbd7b15-802f-4638-90d7-04b92c52a59b|TST-CYB-CTL041-02|Prueba de capacidad real de escalamiento y reemplazo en soporte|Evaluar si existen rutas reales de escalamiento y respaldo para cubrir fallas en equipos o proveedores de soporte.|La muestra evidencia escalamiento funcional y reemplazo efectivo sin dependencia unica no mitigada.|Existen funciones de soporte sin respaldo, sin escalamiento eficaz o excesivamente dependientes de un unico recurso.|{"steps":[{"order":1,"action":"identificar funciones de soporte con alta criticidad o dependencia especializada"},{"order":2,"action":"revisar matrices de escalamiento y backups funcionales"},{"order":3,"action":"seleccionar casos reales o simulados de indisponibilidad del soporte principal"},{"order":4,"action":"validar si el reemplazo o escalamiento funciono en la practica"},{"order":5,"action":"documentar dependencia excesiva en una sola persona, proveedor o turno"}]}|Matrices de escalamiento, backups funcionales, tickets, cronologias, turnos, evidencias de respuesta alternativa.|Debe existir evidencia de funcionamiento real de la ruta de reemplazo o escalamiento.|Muy alineado con Kiriox: detecta nodos humanos o contractuales críticos.|Prueba estructural sobre continuidad del soporte.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000013|6f30d135-601c-4e74-8a1d-05b65c563734|TST-CYB-CTL042-01|Prueba operativa de proteccion fisica y orden del cableado critico|Verificar que el cableado critico se encuentra protegido, identificado y dispuesto de forma que reduzca riesgo de daño, desconexion o manipulación no autorizada.|La muestra evidencia cableado ordenado, identificado y protegido en zonas criticas.|Existen cables expuestos, sin identificacion, con riesgo de desconexion, daño o acceso no controlado.|{"steps":[{"order":1,"action":"identificar zonas con cableado critico como datacenters, cuartos de telecomunicaciones, racks y canales troncales"},{"order":2,"action":"seleccionar muestra de tramos, racks o puntos de concentracion"},{"order":3,"action":"validar proteccion fisica, orden, identificacion y acceso restringido"},{"order":4,"action":"revisar incidentes o hallazgos previos asociados a cableado"},{"order":5,"action":"documentar exposiciones, desorden o riesgos de interrupcion"}]}|Inspecciones, evidencias fotograficas controladas, inventarios de puertos o troncales, hallazgos, tickets correctivos.|La muestra debe permitir comprobar tanto identificacion como proteccion fisica real.|Cableado mal gestionado crea interrupciones silenciosas y fragilidad acumulada.|Prueba fisica simple pero muy reveladora.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000014|6f30d135-601c-4e74-8a1d-05b65c563734|TST-CYB-CTL042-02|Prueba de tratamiento de incidentes o degradaciones por cableado|Evaluar si la organizacion detecta y corrige oportunamente fallas o degradaciones asociadas a cableado critico.|Los casos revisados muestran deteccion, identificacion del tramo afectado, correccion y verificacion posterior.|Las fallas por cableado se diagnostican tarde, se corrigen sin trazabilidad o recurren por mala gestion estructural.|{"steps":[{"order":1,"action":"solicitar incidentes, mantenimientos o fallas del periodo asociados a cableado o conectividad fisica"},{"order":2,"action":"seleccionar muestra por impacto y recurrencia"},{"order":3,"action":"validar deteccion, diagnostico, correccion y fecha de restablecimiento"},{"order":4,"action":"confirmar si existio verificacion posterior y actualizacion de identificacion o inventario"},{"order":5,"action":"documentar recurrencias o cierres sin solucion estructural"}]}|Tickets, bitacoras de mantenimiento, cronologias, evidencias de correccion, verificaciones posteriores.|Cada caso debe mostrar tanto tratamiento como aprendizaje o correccion estable.|No basta reparar; importa evitar la repeticion por desorden físico.|Conecta proteccion fisica con continuidad operacional.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000015|d980e426-8def-4f2f-8d9f-4a9b5957bbe5|TST-CYB-CTL043-01|Prueba operativa de mantenimiento planificado de equipos criticos|Verificar que los equipos criticos reciben mantenimiento preventivo o planificado dentro de frecuencias definidas y con trazabilidad suficiente.|La muestra evidencia mantenimientos ejecutados en tiempo, con alcance definido y cierre verificable.|Los mantenimientos se incumplen, se registran sin ejecucion real o no cubren equipos criticos.|{"steps":[{"order":1,"action":"identificar equipos criticos sujetos a mantenimiento planificado"},{"order":2,"action":"solicitar plan o calendario y registros ejecutados del periodo"},{"order":3,"action":"seleccionar muestra por criticidad y tipo de equipo"},{"order":4,"action":"validar fecha planificada, fecha real, alcance y resultado del mantenimiento"},{"order":5,"action":"documentar atrasos, omisiones o cierres sin evidencia suficiente"}]}|Calendarios, bitacoras de mantenimiento, ordenes de trabajo, reportes tecnicos, evidencias de cierre.|Cada equipo muestreado debe mostrar frecuencia definida y mantenimiento efectivamente ejecutado.|Mantenimiento no ejecutado convierte el activo critico en fragilidad latente.|Prueba operativa de disciplina sobre equipos críticos.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000016|d980e426-8def-4f2f-8d9f-4a9b5957bbe5|TST-CYB-CTL043-02|Prueba de tratamiento y verificacion posterior a mantenimiento correctivo|Evaluar si las intervenciones correctivas sobre equipos criticos resuelven la falla y se verifican despues de ejecutarse.|Los casos revisados muestran correccion efectiva, prueba posterior y cierre sustentado.|Las correcciones se cierran sin prueba, la falla reaparece o queda degradacion residual no tratada.|{"steps":[{"order":1,"action":"solicitar mantenimientos correctivos del periodo sobre equipos criticos"},{"order":2,"action":"seleccionar muestra por impacto, recurrencia y tipo de activo"},{"order":3,"action":"validar diagnostico, accion correctiva, fecha de restablecimiento y responsable"},{"order":4,"action":"confirmar si hubo prueba posterior o monitoreo de estabilidad"},{"order":5,"action":"documentar recurrencia, cierres debiles o ausencia de verificacion"}]}|Tickets, ordenes correctivas, pruebas post cambio, bitacoras, reportes de estabilidad, cierres.|Cada caso debe evidenciar que el equipo quedo funcional y estable despues de la correccion.|La reparacion sin prueba es una presuncion, no un control.|Muy util para separar mantenimiento formal de mantenimiento efectivo.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000017|6b4538cb-81c4-41a5-95b8-1ba8a09273e6|TST-CYB-CTL044-01|Prueba operativa de borrado seguro o sanitizacion de activos retirados|Verificar que los activos retirados, reutilizados o dados de baja reciben borrado seguro o sanitizacion verificable antes de su disposicion o reasignacion.|La muestra evidencia sanitizacion ejecutada con metodo definido, trazabilidad y cierre antes de la salida o reutilizacion del activo.|Los activos se retiran, reutilizan o disponen sin evidencia suficiente de borrado seguro.|{"steps":[{"order":1,"action":"obtener activos dados de baja, reutilizados o reasignados en el periodo"},{"order":2,"action":"seleccionar muestra por tipo de medio y sensibilidad del contenido potencial"},{"order":3,"action":"validar metodo de borrado o sanitizacion aplicado y fecha de ejecucion"},{"order":4,"action":"confirmar que el proceso ocurrio antes de la salida, venta, destruccion o reasignacion"},{"order":5,"action":"documentar activos sin prueba de sanitizacion o con metodo insuficiente"}]}|Actas de baja, certificados de borrado o destruccion, tickets, bitacoras, cadena de custodia, evidencias de proceso.|Cada activo muestreado debe mostrar metodo, fecha, responsable y evidencia antes de disposicion o reutilizacion.|El activo retirado sin sanitizacion es fuga diferida de informacion.|Control esencial para cierre del ciclo de vida del activo.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000018|6b4538cb-81c4-41a5-95b8-1ba8a09273e6|TST-CYB-CTL044-02|Prueba de trazabilidad y custodia en disposicion final de activos|Evaluar si la disposicion final de activos mantiene cadena de custodia, autorizacion y trazabilidad hasta su cierre definitivo.|La muestra evidencia custodia controlada, autorizacion, transferencia o destruccion trazable y cierre final del activo.|Los activos salen sin trazabilidad, sin autorizacion o sin confirmacion de disposicion final controlada.|{"steps":[{"order":1,"action":"solicitar bajas o disposiciones finales del periodo"},{"order":2,"action":"seleccionar muestra por criticidad y tipo de activo"},{"order":3,"action":"validar autorizacion, cadena de custodia, traslado y destino final"},{"order":4,"action":"confirmar si existe evidencia de recepcion, destruccion o cierre del tercero interviniente"},{"order":5,"action":"documentar rupturas de custodia o activos sin cierre final demostrable"}]}|Actas, guias de traslado, certificados de destruccion, autorizaciones, contratos con terceros, bitacoras.|Debe poder reconstruirse el recorrido del activo hasta su cierre final.|Sin trazabilidad de custodia, el borrado seguro queda incompleto como control.|Prueba de cierre material del activo.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000019|d392a294-5785-4258-aa6b-67ab16ed04f8|TST-CYB-CTL045-01|Prueba operativa de proteccion efectiva de endpoints|Verificar que los endpoints corporativos operan con protecciones efectivas activas y no solo con herramientas desplegadas nominalmente.|La muestra evidencia protecciones activas como EDR o equivalente, cifrado, politicas, bloqueo y estado de salud conforme.|Los endpoints presentan agentes inactivos, protecciones degradadas, falta de enforcement o desviaciones persistentes.|{"steps":[{"order":1,"action":"identificar el universo de endpoints corporativos y sus controles esperados"},{"order":2,"action":"seleccionar muestra por tipo de dispositivo, criticidad, ubicacion y modalidad de trabajo"},{"order":3,"action":"validar estado real de EDR, cifrado, actualizaciones, politicas, bloqueo y otros controles definidos"},{"order":4,"action":"revisar eventos de no conformidad o degradacion del periodo"},{"order":5,"action":"documentar endpoints fuera de control, sin agente activo o con protecciones incompletas"}]}|Consolas EDR o MDM, inventario, reportes de conformidad, configuraciones, eventos de incumplimiento, tickets.|Cada endpoint muestreado debe demostrar estado de proteccion real y no solo asignacion de politica.|Herramienta instalada no equivale a control funcionando.|Prueba base del control real sobre endpoint.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000020|d392a294-5785-4258-aa6b-67ab16ed04f8|TST-CYB-CTL045-02|Prueba de deteccion y remediacion de desviaciones en endpoints|Evaluar si las desviaciones de seguridad en endpoints se detectan y corrigen en tiempos razonables y con evidencia de cierre real.|La muestra evidencia deteccion de incumplimientos, tratamiento oportuno y retorno verificable a estado conforme.|Las desviaciones permanecen abiertas, se corrigen tarde o se cierran sin comprobacion suficiente.|{"steps":[{"order":1,"action":"solicitar eventos o hallazgos del periodo asociados a endpoints fuera de conformidad"},{"order":2,"action":"seleccionar muestra por severidad, antiguedad y tipo de incumplimiento"},{"order":3,"action":"validar deteccion, asignacion, remediacion y fecha de cierre"},{"order":4,"action":"confirmar que el endpoint regreso a estado conforme mediante evidencia posterior"},{"order":5,"action":"documentar recurrencias, tiempos excesivos o cierres sin prueba"}]}|Tickets, alertas EDR o MDM, bitacoras de remediacion, reportes posteriores de conformidad, dashboards.|Cada caso debe mostrar el antes, la accion y la conformidad posterior comprobada.|Control fuerte para medir operacion y no solo despliegue de herramienta.|Muy util para tendencia y efectividad sostenida.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
b9000001-4a22-4d8f-b001-c1a100000021|d392a294-5785-4258-aa6b-67ab16ed04f8|TST-CYB-CTL045-03|Prueba de cobertura real de proteccion de endpoints sobre universo activo|Evaluar si la proteccion de endpoints cubre efectivamente el universo activo relevante y no solo una fraccion parcial del entorno.|La organizacion evidencia alta cobertura sobre endpoints activos y tratamiento formal de excepciones o dispositivos no cubiertos.|Existen endpoints activos fuera del esquema de proteccion, sin excepcion formal o sin plan de cierre.|{"steps":[{"order":1,"action":"obtener universo activo de endpoints desde inventario y fuentes operativas"},{"order":2,"action":"comparar universo activo contra cobertura real de las herramientas o controles de endpoint"},{"order":3,"action":"identificar dispositivos no cubiertos, duplicados o huerfanos"},{"order":4,"action":"validar si existe excepcion formal o plan de cierre para las brechas"},{"order":5,"action":"documentar porcentaje, criticidad y riesgo de la brecha de cobertura"}]}|Inventario, CMDB, EDR, MDM, directorio, conciliaciones, excepciones aprobadas, planes de cierre.|Debe poder cuantificarse cobertura real y brecha residual sobre universo activo.|Este test evita el falso positivo de “tenemos plataforma” cuando la cobertura es parcial.|Muy alineado con Kiriox: cobertura lineal y punto ciego estructural.|draft|true|NULL|2026-03-29 00:00:00|NULL|2026-03-29 00:00:00|2026-03-29 00:00:00
\.

with ins as (
  insert into core.control_evaluation_catalog (
    id,
    control_id,
    dimension_id,
    code,
    title,
    evaluation_guidance,
    pass_criteria,
    fail_criteria,
    evaluator_steps,
    evidence_required,
    evidence_min_spec,
    sample_guidance,
    notes,
    status,
    is_active,
    framework_version_id,
    effective_from,
    effective_to,
    created_at,
    updated_at
  )
  select
    t.id::uuid,
    t.control_id::uuid,
    'c288a358-ef38-4c64-960b-43fffb9a3412'::uuid as dimension_id,
    t.code,
    t.title,
    t.evaluation_guidance,
    t.pass_criteria,
    t.fail_criteria,
    t.evaluator_steps::jsonb,
    t.evidence_required,
    t.evidence_min_spec,
    t.sample_guidance,
    t.notes,
    t.status,
    t.is_active::boolean,
    t.framework_version_id::uuid,
    t.effective_from::timestamptz,
    t.effective_to::timestamptz,
    t.created_at::timestamptz,
    t.updated_at::timestamptz
  from tmp_cyb_group_8_9 t
  where not exists (
    select 1
    from core.control_evaluation_catalog c
    where c.id = t.id::uuid
       or c.code = t.code
  )
  returning 1
)
select count(*) as inserted_rows
from ins;

commit;
